version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx content/"

conda:
  environment: environments/py-3.10-linux-64-dev.conda.lock.yml

python:
  install:
    - method: pip
      path: . --no-deps
